on: workflow_dispatch

jobs:
  action_integration_test:
    runs-on: ubuntu-latest
    name: Action Integration Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Display current file system structure
        run: tree

      - name: Install dependencies
        run: npm install

      - name: Build action
        run: npm run package

      - name: Copy action.yml to `src`
        run: cp src/action.yml dist/

      - name: Schema validator action
        uses: ./dist
        with:
          schema-url: 'https://raw.githubusercontent.com/Biswajee/Azure-DevOps-Extensions-Workshop/master/src/package.json'
          json-url: 'https://raw.githubusercontent.com/Biswajee/Azure-DevOps-Extensions-Workshop/master/src/package.json'
